version: '3.7'
services:
  app:
    container_name: app
    build: ./backend-fiber/
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres
      - mongoDB
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: always
    networks: 
      - backend

  redis:
    container_name: redis
    hostname: redis
    image: redis:latest
    command: --port 6380
    ports:
      - "6380:6380"
    restart: always
    networks: 
      - backend

  postgres:
    container_name: postgres
    hostname: postgres
    image: 'postgres:latest'
    ports:
      - 5432:5432
    networks: 
      - backend

    environment:
      POSTGRES_USER: simvino # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: test  # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: simvino # The PostgreSQL default database (automatically created at first launch)
  mongoDB:
    container_name: mongo
    image: mongo
    hostname: mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secrets
    ports: 
      - 27019:27019
    networks: 
      - backend

networks:
  backend:
    driver: "bridge"