// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Login struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NewTransaction struct {
	Value    float64 `json:"value"`
	Currency string  `json:"currency"`
}

type NewUser struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Transaction struct {
	Value    float64 `json:"value"`
	Currency string  `json:"currency"`
}

type User struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
