CREATE Table USERS_ASSETS(
  CryptoHisId BIGSERIAL PRIMARY KEY,
  ASSET TEXT,
  PRICE INT NOT NULL
  DATE DATE NOT NULL DEFAULT  CURRENT_DATE,
  CONSTRAINT fk_crypto_id
      FOREIGN KEY(fk_crypto_id) 
	  REFERENCES CRYPTO(cryptoId)
);