redis: 
  addr: localhost:6380
  password: test123
  db: 1

postgres: 
  host: localhost
  port: 5432
  user: simvino
  password: test
  dbname: simvino

mongo: 
  host: mongodb://localhost:27017

password: 
  pepper: $NW^6#5@e4u64nPQ
